### ISSUE TITLE
Don't use [*]Names fields in data

### ISSUE THREAD

**Issue by nestdotland** [nestdotland/api#1]
Currently, getting data related to module uploads is done like so:

```graphql
{
  package(name: "eggs") {
    packageUploadNames
  }
}
```

As you can see, if you want to get the uploads, one must query again using the names.

"Names" should be removed, including for users with the packageNames fields and instead allow these fields to directly query the packages and package uploads.

**Comment by divy-work** [comment]
- [x] Direct queries to packages have been added.

**Comment by divy-work** [comment]
- [ ] Direct query to users added too.

**Comment by zorbyte** [comment]
To summarise:

There should not be a seperate query for `packageUploads` like the following:

```graphql
{
  packageUploads(name: "eggs@v0.1.0") {}
}
 ```

Instead:

```graphql
{
  packages(name: "eggs") {
    uploads(name: "0.1.0") {}
  }
}
 ```

The `packageNames` field on the packages object would be removed in favour of this. We should also support querying a certain amount of uploads and potentially pagination of them.

This same process should be applied to the `packageNames` field on the user object as well.

**Comment by zorbyte** [comment]
I might change the issue name and description to reflect this.

**Comment by divy-work** [comment]
@zorbyte https://github.com/nestdotland/api/commit/f606dc1109d90fe8a38ba4bfbda2f58f6c0fb4f5 has been merged. It adds:
```graphql
{
  packages(name: "eggs") {
    uploads(name: "0.1.0") {
      name
    }
  }
}
```

and 

```graphql
{
  packages(name: "eggs") {
    uploads {
      name
    }
  }
}
```

And removes the global query for `uploads`

**Comment by divy-work** [comment]
@zorbyte Can we close this for now we have https://github.com/nestdotland/api/pull/32 merged.
