### ISSUE TITLE
Community module validation

### ISSUE THREAD

**Issue by t8** [nestdotland/api#16]
@MartonDev and I are planning to implement a community modules field to nest.land, but this will require some security measures that don't currently exist in both `x-node` and `x-rust`. 

We're going to need to find a way to validate the integrity of the module that the user is uploading versus the official module itself in source control. We think that the easiest way to go about doing this is by scanning through each file in the file tree and comparing it to the file in source control, though this could end up being a laborious process for the API. Another possible method would be to upload a module through a GitHub url directly, so there would be no validation other than ensuring the module isn't a fork of the official. 

Regardless, this functionality will need to be implemented into the rust API. I'm marking this as a low priority because I don't think that this should be finished by the time the API is ready for `0.1.0`, but it is something that we should be mindful of. I'm going to be making an issue in the CLI repository as well, as this feature will also concern og.

I recognize that this could end up being a monstrous task, so don't feel like this has to get done any time soon. When it does get done, it will be a very welcomed addition to the service!

**Comment by MartonDev** [comment]
The direct upload from the GitHub url is an even better option. I haven't thought about that.

**Comment by divy-work** [comment]
@t8 It can be easy to implement if we use the GitHub URL

**Comment by MartonDev** [comment]
I just realized, that will have problems. How can the user set the egg.json values if they can only give an url?

**Comment by maximousblk** [comment]
How about user only sets the egg.json values and repo url (or git url) is one of the values?

**Comment by MartonDev** [comment]
We could do that maybe

**Comment by t8** [comment]
Here's the thing --> If a user decides to publish a "community module," source control will be required to verify the validity of the module. We would only need to require the repository and entry fields in `egg.json` because we could pull the other registry information straight through the GitHub API. We can add support for GitLab, Bitbucket, etc. in the future. 

For example, here is all of the information we could gather just by assuming we're using the GitHub API and considering it a community module:

- **title**: repository name
- **description**: repository description field
- **version**: latest release (or optionally allow them to specify a release)
- **stable**: N/A (no way to verify this so remove the field completely)
- **unlisted**: false
- **fmt**: false
- **files**: everything included except items in the `.gitignore`

**Comment by divy-work** [comment]
@t8 So you suggest we have a different db table for this?

**Comment by t8** [comment]
@divy-work I think that would be a good idea, yes.

**Comment by MartonDev** [comment]
Closed due to ethical, legal and malware concerns.
