### ISSUE TITLE
Automatic Deployments

### ISSUE THREAD

**Issue by divy-work** [nestdotland/api#17]
Since releases for all platforms will be done on the CI, We'll have to automate that just like how autopilot does it - https://github.com/divy-work/autopilot-deno

So everytime we want to release a new version, we make an increment at a `version.ts` that will trigger the CI to create a draft release.

__EDIT__:
Release CI has been implemented. Reopened this issue for automatic deployments.

**Comment by t8** [comment]
This would be great. It would be awesome if we could use this in tandem with automatic deployments to Digital Ocean.

I'm not quite sure how we'd go about doing this, but I'm sure there is a way?

**Comment by divy-work** [comment]
We could setup a webhook based deployment to digitalocean.
