### ISSUE TITLE
User login with session, user API, new routes

### ISSUE THREAD

**Issue by MartonDev** [nestdotland/api#21]
**Is your feature request related to a problem? If so, please describe.**
I started working on a login/user profile feature for the front-end. This requires an API
**Describe the solution you'd like**
A user API with the following routes:
- `/api/user/login` and `/api/user/register`
- `/api/user/modules` to list all modules
- `/api/user/:username` to get userinfo

An `email` field would also be great, because let's face it, yes we want privacy, but for account recoveries, etc. we need the users' email.

Obivously, this is not hight-priority, don't want to ruin your roadmap, but we'll need to implement this in the future.

**Comment by divy-work** [comment]
@MartonDev All the API routes you need are fulfilled by the Graphql API already.

* login and registration for user can be done using `user` query and `createUser` mutation.

https://github.com/nestdotland/api/blob/master/docs/queries/user.md 
and https://github.com/nestdotland/api/blob/master/docs/mutations/user_mutation.md

* Complete module list can be retrieved using `modules` query.
* Userinfo of the username can be queried using `userByName` query.

Sending these query to the api from the website is very easy. 
```js
var myHeaders = new Headers();
myHeaders.append("Content-Type", "application/json");
  var graphql = JSON.stringify({
    query: "QUERY HERE", // put your query or mutation here
    variables: {}
  })
  var requestOptions = {
    method: 'POST',
    headers: myHeaders,
    body: graphql,
  };
  return await fetch("http://localhost:8080/graphql", requestOptions)
}
```

As far as the `email` column is concerned, it can be safely added without disturbing the current env.
Tell me if you want me to clarify something. 

Also, Yolk (the API client) will be compatible with web too..so sending queries will be more easier. :smile:

**Comment by t8** [comment]
We need to have a discussion about the `email` field before it is implemented. Let's add this as a topic of conversation on our next meeting. 

A major benefit of the service is that we don't require users to create "accounts" and we don't collect data such as emails. Adding an `email` field may jeopardize this massive benefit.

**Comment by MartonDev** [comment]
Alright i agree, let's talk about that

**Comment by MartonDev** [comment]
Returning to this, as I don't really know how the api is going and if you're planning to add the `/api/user/:username/modules` route. It is needed so the front end doesn't have to parse all modules in order to list the user's modules.
I would also request a module search modiles route and a paginated all modules route to be added (same reason, so that the front end doesn't have to parse the info).
I know this is a lot, so obviously this is not high priority. I just want to know if this is possible
