### ISSUE TITLE
Captcha support

### ISSUE THREAD

**Issue by zorbyte** [nestdotland/api#37]
**Is your feature request related to a problem? If so, please describe.**
The website currently uses an internal serverless function for reCaptcha verification.

**Describe the solution you'd like**
This responsibility should be delegated to the API, this way we no longer depend on Vercel's
serverless functions with the site

**Describe alternatives you've considered**
Keeping it on the site, although that would pollute the purpose of the site or using a separate service.
Using a separate service would be useful for ensuring everything is a microservice and segregated,
but it is not required and quite a pedantic solution.

**Comment by zorbyte** [comment]
@t8

**Comment by divy-work** [comment]
@zorbyte How are we going to do that?

**Comment by zorbyte** [comment]
Using the google recaptcha API. Check nestdotland/nest.land#master/api/captcha.js.

**Comment by t8** [comment]
This would be beneficial for code organization, but I don't think this should be a priority in the foreseeable future.
